GET http://localhost:3000/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFzaCIsImlhdCI6MTY5NDQyODY2OCwiZXhwIjoxNjk0NDI4NjkzfQ.HOu1LkV0XkVkEgnGlsRo3SR5Oumh0mS5vu8KKBPX0Ho

###
POST http://localhost:4000/token 
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFzaCIsImlhdCI6MTY5NDQyOTMwNX0.NZlOlSflbng1ooL8ISe6_in93HLwJ_MZ6Qcags0_8gw"
}


###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFzaCIsImlhdCI6MTY5NDQyOTMwNX0.NZlOlSflbng1ooL8ISe6_in93HLwJ_MZ6Qcags0_8gw"
}



###
POST http://localhost:4000/login
Content-Type:application/json

{
    "username":"Yash"
}


