

###

GET  http://localhost:8000/users
Content-Type: application/json

{
    "name":"Shambhu",
    "password":"Shambhu@ddlkeiur3874;lskdj"
}


###

POST http://localhost:8000/users/login
Content-Type: application/json

{
    "name":"Shambhu",
    "password":"Shambhu@ddlkeiur3874;lskdj"
    
}